# Generated by Django 5.0.4 on 2024-05-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_firstname_student_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
